### ISSUE TITLE
Reduce image size

### ISSUE THREAD

**Issue by annybs** [WeareJH/workflow#109]
Copy-pasting from the Slack conversation:

> @annybs on the topic of docker chewing through disk space - i suspect one of our key 'problems' is that the official php images are ~700mb. for my own purposes on my week off, i spent a little time working on alpine-based php5/7 images, and these come out at <100mb with most every magento dependency preinstalled, plus xdebug https://github.com/annybs/php-alpine
>
> i'm not sure these are adequate for jh purposes because the php version is pretty loose, based on what's available in alpine repos rather than compiled from a specific source - which at the moment, means that php 7.2 is not available. but perhaps curating our own base images is something for us to think about, in the interest of reducing the size of project images on dev machines - if i have 10 projects installed at ~100mb each, rather than the current ~700mb, then that's already 7gb saved and a much less bloated docker disk
>
> n.b. i'm aware that the official php image has alpine variant tags, but for some reason php is compiled with a non-standard ini dir which means packages installed from apk won't be recognised as they're put in the wrong place https://github.com/docker-library/php/blob/master/7.2/alpine3.7/fpm/Dockerfile#L40

> @maxbucknell Not all Magento versions work with Alpine. https://github.com/magento/magento2/issues/8070

I think this is a worthy goal despite potential technical issues, and maybe something worth visiting in the future (which is why I'm creating an issue here, rather than leaving the conversation to scroll away into the void!)

**Comment by shakyShane** [comment]
@annybs so did you try to swap out how we do it already for https://github.com/annybs/php-alpine ? if so, what was the outcome?

**Comment by annybs** [comment]
I haven't tried running one of our projects on my Alpine images yet. In fact I think I broke them last night while fiddling with the Dockerfiles 😂 

I think for our purposes, it would be better to try to create comprehensive images based on the official PHP images. This doesn't reduce file size per image, but it might mean we don't need to create an individual image per project, ergo saving overall space used even if the image remains large.

**Comment by annybs** [comment]
@shakyShane @mikeymike Got a project running on `wearejh/php:5.6` (I was going to name it before I remembered this is a public repo!)

https://github.com/WeareJH/php

This image works perfectly in my testing so far, and seems like a good candidate to drop straight in to all M1 projects.

It's not Alpine, which would deliver a _huge_ reduction in image size, but it's still sub-300MB for a single shared image, as opposed to 600MB+ per project. Maybe that's something we could work on later after getting projects switched over.

**Comment by annybs** [comment]
After actually checking, I seem to have misremembered how big Ubuntu-based images get to be:

```
$ docker image ls | grep wearejh/php | awk '{print $2 " " $(NF)}'
5.6 758MB
```

Alpine would be under 100MB for sure. Still an improvement, though.

**Comment by mikeymike** [comment]
A shared image for M1 projects (not using composer) seems good to me. 

In the long run however unless we switch distro for Magento 2 projects we're still going to have individual projects with large images, even if we have a base image that only really helps the speed of builds and most likely takes up more space cause you need to store that plus the resulting project images. 

If we can build stable alpine images for PHP7 then big thumbs up from me, the only caveat is peeps using `workflow ssh` will be dumped into `sh` and not `bash` unless we look at making the `sh` experience a little nicer there will likely be some complaints 😂

**Comment by annybs** [comment]
Not disputing that. Our main advancement in creating a wearejh/php image (for 5.6 so far, anyway) is that we can remove a lot of additional installation steps from Dockerfiles, so that we don't have to bundle them in Workflow.

I'd really like to move to Alpine, which in general is a much cleaner, quicker experience. It also has certain benefits such as being able to do:

```
RUN apk add --no-cache --virtual build-tools \
    autoconf \
    gcc \
    php5-dev

# install some stuff, e.g. xdebug

RUN apk del build-tools
```

In other words, install build dependencies in a virtual package, then remove them when they're no longer required - thereby making the final images considerably smaller. I'll bet that our Ubuntu images are so large partly because dependencies are not removed, and to a lesser extent because of apt cache storage.

`sh` is not as clever as `bash` but I think it's a perfectly viable trade-off, as ideally we shouldn't be relying heavily on in-container traversal, anyway.

**Comment by annybs** [comment]
Which I'm working on in my own image by the way; Xdebug for PHP 5 can't be installed from apk, and pecl isn't available, so I have to compile the source 😂 

https://github.com/annybs/php-fpm-alpine/blob/php5-xdebug/5.6/Dockerfile#L33-L46

(Which leads me to begin to think maybe I'm just better off using the Alpine variants of the official repo and avoiding apk altogether, but I'm learning some stuff from that project, so not giving up on it yet)
